apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dockstack
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: dockstack
  MYSQL_USER: dockuser
  MYSQL_PASSWORD: dockpassword